// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQKkPj19MFu0kLoFyyXoOrLj6BHumTdI',
    appId: '1:695529832189:web:7464ea552a5ca17c3b4894',
    messagingSenderId: '695529832189',
    projectId: 'datn-foodecommerce',
    authDomain: 'datn-foodecommerce.firebaseapp.com',
    storageBucket: 'datn-foodecommerce.firebasestorage.app',
    measurementId: 'G-FJLZ15VHD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hfur_35_Zeo7ZbbyXlaOLSWkg6LIoTo',
    appId: '1:695529832189:android:0ea34ab145c59ac43b4894',
    messagingSenderId: '695529832189',
    projectId: 'datn-foodecommerce',
    storageBucket: 'datn-foodecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgJ_n8cLDUfnoYQUk-VuMAslwYsNEJgrI',
    appId: '1:695529832189:ios:05e4507b04dec7d53b4894',
    messagingSenderId: '695529832189',
    projectId: 'datn-foodecommerce',
    storageBucket: 'datn-foodecommerce.firebasestorage.app',
    iosBundleId: 'com.example.datnFoodecommerceFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgJ_n8cLDUfnoYQUk-VuMAslwYsNEJgrI',
    appId: '1:695529832189:ios:05e4507b04dec7d53b4894',
    messagingSenderId: '695529832189',
    projectId: 'datn-foodecommerce',
    storageBucket: 'datn-foodecommerce.firebasestorage.app',
    iosBundleId: 'com.example.datnFoodecommerceFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQKkPj19MFu0kLoFyyXoOrLj6BHumTdI',
    appId: '1:695529832189:web:bf5cb6742ce9238b3b4894',
    messagingSenderId: '695529832189',
    projectId: 'datn-foodecommerce',
    authDomain: 'datn-foodecommerce.firebaseapp.com',
    storageBucket: 'datn-foodecommerce.firebasestorage.app',
    measurementId: 'G-FYX6Z10RQN',
  );

}